use_default_settings: true
server:
  secret_key: "megasecretkey" # change this!
  limiter: true # can be disabled for a private instance
  image_proxy: true
search:
  formats:
    - html
    - json
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
