replicaCount: 1

searxng:
  enabled: true
  env:
    INSTANCE_NAME: "my-instance"
    BASE_URL: "http://localhost:8080/"
    AUTOCOMPLETE: "false"

envFrom: {}
env: {}

image:
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

startupProbe:
  enabled: true
  custom: false
  spec: {}
livenessProbe:
  enabled: true
  custom: false
  spec: {}
readinessProbe:
  custom: false
  enabled: true
  spec: {}

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
