name: Build App

on:
  push:
    branches:
      - main
    paths:
      - "deploy/*.Dockerfile"
      - "*.json"
      - "*.ts"
      - pnpm-lock.yaml
      - "*.js"
      - "src/**"
      - "prisma/**"
      - "static/**"
      - ".gitignore"
  workflow_dispatch:

jobs:
  build-migrate:
    name: Build and push migration Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Log into registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/brunostjohn/perplexideez/migrate
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=v1.0.0
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.8.0
        with:
          platforms: linux/amd64,linux/arm64
          file: deploy/db-migrate.Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  build-app:
    name: Build and push app Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Log into registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/brunostjohn/perplexideez/app
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=v1.0.0
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.8.0
        with:
          platforms: linux/amd64,linux/arm64
          file: deploy/app.Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
