name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "deploy/kubernetes/**"
  workflow_dispatch:

jobs:
  release-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply@github.com"
      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_OWNER: brunostjohn
          CR_GIT_REPO: charts
          CR_PACKAGE_PATH: deploy
